name: Build and Publish
on:
  push:
    branches: [ "master" ]

jobs:
  build-and-publish:
    name: Build, Version update, Release and Publish
    runs-on: ubuntu-latest
    concurrency: ci-${{ github.ref }}
    permissions:
      contents: write
      pull-requests: read
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    steps:
      - uses: actions/checkout@v4

      - name: Set up Java 11
        uses: actions/setup-java@v4
        with:
          java-version: '11'
          distribution: 'temurin'

      - name: Build with Maven
        run: mvn package

      - name: Increment version
        id: increment-version
        uses: RichardInnocent/semantic-versioning-maven@v0.1.0

      - name: Print if version changed
        if: steps.increment-version.outputs.previous-version != steps.increment-version.outputs.new-version
        run: echo "The new version is now $new_version"
        env:
          new_version: ${{ steps.increment-version.outputs.new-version }}

      - name: Create release
        if: steps.increment-version.outputs.previous-version != steps.increment-version.outputs.new-version
        uses: actions/create-release@v1
        with:
          tag_name: 'v${{ steps.increment-version.outputs.new-version }}'
          release_name: ${{ steps.increment-version.outputs.new-version }}

      - name: Import GPG Key
        if: steps.increment-version.outputs.previous-version != steps.increment-version.outputs.new-version
        uses: crazy-max/ghaction-import-gpg@v6
        with:
          gpg_private_key: ${{ secrets.GPG_SIGNING_KEY }}
          passphrase: ${{ secrets.GPG_SIGNING_KEY_PASSWORD }}

      - name: Publish package
        env:
          REPO_USER: ${{ secrets.CENTRAL_TOKEN_USERNAME }}
          REPO_PASSWORD: ${{ secrets.CENTRAL_TOKEN_PASSWORD }}
          GH_PASSPHRASE: ${{ secrets.GPG_SIGNING_KEY_PASSWORD }}
        if: steps.increment-version.outputs.previous-version != steps.increment-version.outputs.new-version
        run: mvn --settings .github/maven-settings.xml deploy